### ISSUE TITLE
Add keystore passwords as secrets not plaintext

### ISSUE THREAD

**Issue by murphymagic** [licenseware/charts#20]
If I want to turn on TLS, I have to add passwords in plaintext as shown below. Instead of doing this, can the passwords reference a secret that contains the actual password?

`

configMapPairs:
    KSQL_BOOTSTRAP_SERVERS: "SSL://kafka:19092"
    KSQL_OPTS: |-
      ...
      -Dsecurity.protocol=SSL
      -Dssl.truststore.password=P@ssw0rd1
      -Dssl.truststore.location=/tls/kafka.client.truststore.jks
      -Dssl.keystore.location=/tls/keystore.p12
      -Dssl.keystore.password=P@ssw0rd1
      ...
`

**Comment by meysam81** [comment]
Thanks for showing interest and using the package @murphymagic.
You can pass your secrets to `secretPairs`, which is still plaintext from the terminal but base64-encoded in the `Secret` resource [and encrypted if your cluster encrypts secrets].

**Comment by murphymagic** [comment]
Thank you for the response @meysam81 
I should have clarified that I am using the ksqldb chart - I think the secretPair you are referring to is in licenseware-sdk-v2 chart.
As far as I can tell, there is no way of passing in secrets to the ksqldb chart - the configMapPairs excerpt I posted above along with KSQL_OPTS is the only way I can think of, but it is in plaintext...

**Comment by meysam81** [comment]
@murphymagic Please let me know if the proposed change can satisfy your needs.
If so, I'll merge it in and you'll be able to use it as instructed earlier.

**Comment by murphymagic** [comment]
Thanks for this @meysam81 
I think I can work with this. 
I won't use secretPairs at all, since I don't want that data showing up in the values.yaml.
But  I can separately deploy my own ksqldb secret with sensitive information and that will get picked up by the ksqldb deployment.
I can put non-sensitive info in the ConfigMapPairs as I am already doing..

**Comment by meysam81** [comment]
@murphymagic 
Could this one be what you're looking for? https://github.com/licenseware/charts/pull/21/files#diff-fb29155af4d133889faf7ab1ba6cbc7040915564df932d627f2e0e8ac61258c2R119

**Comment by ttimot24** [comment]
Can you please add an example, how can I configure SASL user and password?

**Comment by meysam81** [comment]
@ttimot24 

```yaml
# my-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  KSQL_OPTS: |-
    -Dsecurity.protocol=SSL
    -Dssl.truststore.password=P@ssw0rd1
    -Dssl.truststore.location=/tls/kafka.client.truststore.jks
    -Dssl.keystore.location=/tls/keystore.p12
    -Dssl.keystore.password=P@ssw0rd1
```

```yml
# ksqldb-values.yml
extraEnvFrom:
  - secretRef:
      name: my-secret
```

In a real-world scenario you would use [External Secrets](https://external-secrets.io/) or other alternatives, but this is a simplified version:

```shell
kubectl apply -f my-secret.yml
helm install ksqldb licenseware/ksqldb --version 0.4.1 -f ksqldb-values.yml
```

## Further Reading

If you need help setting up External Secrets:

- <https://developer-friendly.blog/blog/2024/04/29/external-secrets-operator-fetching-aws-ssm-parameters-into-azure-aks/>
