### ISSUE TITLE
Add option to use environment variables from secretRef in kafka-connect

### ISSUE THREAD

**Issue by 1DIce** [licenseware/charts#40]
I want to make sealed secrets available to kafka-connect. That does not seem to be possible, because there is no way to set a `secretRef` like this:

``` yaml
envFrom: 
  - secretRef:
      name: my-secret
```

Is this a missing feature, or is it somehow already possible?
